#pragma config(Motor,  port2,           frontLeft,     tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port3,           frontRight,    tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port4,           backRight,     tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port5,           backLeft,      tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port7,           leftArm,       tmotorVex393_MC29, openLoop, driveLeft)t
#pragma config(Motor,  port8,           rightArm,      tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port10,          claw,          tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)

#include "Vex_Competition_Includes.c"

//Central Functions Section
void controllerBasic();
void turnAround();

//Drive Controller Section
void allOff();
void motorForward();
void motorBackward();
void motorLeftOn();
void motorRightOn();
void driveDirectionDuration(int direction, int duration)

//==================================================================================================
//                     		      T A S K   S E C T I O N
//--------------------------------------------------------------------------------------------------
//			FUNCTIONS:
//				PRE_AUTON
//				AUTONOMOUS
//				USER CONTROL
//==================================================================================================

void pre_auton()
{
	//I DON'T THINK I'M DOING ANYTHING HERE
}

task autonomous()
{
	//1 = Forward
	//2 = Backward
	//3 = MOTOR Left
	//4 = MOTOR Right
	
	driveDirectionDuration(1, 1000);
	driveDirectionDuration(2, 1000);
	
	// Remove this function call once you have "real" code.
	AutonomousCodePlaceholderForTesting();
}

task usercontrol(){
	while (true){
		controllerBasic();
		turnAround();
	// Remove this function call once you have "real" code.
	UserControlCodePlaceholderForTesting();
	}
}

task main{
	while(true){
	}
}

//==================================================================================================
//                           C E N T R A L   F U N C T I O N S   S E C T I O N
//--------------------------------------------------------------------------------------------------
//			MAIN FUNCTIONS:
//				1. CONTROLLER BASIC
//				2. TURN AROUND
//				3. LIFT BASIC
//
//			CONTROLLER INDEX:
//				1. DRIVE CONTROLLER SECTION
//				2. LIFT CONTROLLER SECTION
//==================================================================================================

void controllerBasic(){
	motor[frontLeft] = vexRT(Ch3);
	motor[backLeft] = vexRT(Ch3);

	motor[frontRight] = vexRT(Ch2);
	motor[backRight] = vexRT(Ch2);
	
	while(vexRT[Btn7U] == 1){
		motorForward();
		motorBackward();
		motorLeftOn();
		motorRightOn();
	}
}

void turnAround(){
	if(vexRT[Btn8D] == 1){
		motor[frontLeft] = 127;
		motor[backLeft] = 127;

		motor[frontRight] = -127;
		motor[backRight] = -127;

		wait1Msec(2125);

		allOff();
	}
}

//==================================================================================================
//                             D R I V E   C O N T R O L L E R   S E C T I O N
//==================================================================================================

void allOff(){
	motor[backLeft] = 0;
	motor[backRight] = 0;
	motor[frontLeft] = 0;
	motor[frontRight] = 0;
}

void motorForward(){
	motor[backLeft] = 127;
	motor[backRight] = 127;
	motor[frontLeft] = 127;
	motor[frontRight] = 127;
}

void motorBackward(){
	motor[backLeft] = -127;
	motor[backRight] = -127;
	motor[frontLeft] = -127;
	motor[frontRight] = -127;
}

void motorLeftOn(){
	motor[backLeft] = 127;
	motor[backRight] = 0;
	motor[frontLeft] = 127;
	motor[frontRight] = 0;
}

void motorRightOn(){
	motor[backLeft] = 0;
	motor[backRight] = 127;
	motor[frontLeft] = 0;
	motor[frontRight] = 127;
}

void driveDirectionDuration(int direction, int duration){
	
	//1 = Forward
	//2 = Backward
	//3 = MOTOR Left
	//4 = MOTOR Right
	
	
	if(direction == 1){
		motorForward();
		wait1Msec(duration);
	}
	else if(direction == 2){
		motorBackward(duration);
		wait1Msec(duration);
	}
	else if(direction == 3){
		motorLeftOn(duration);
		wait1Msec(duration);
	}
	else if(direction == 4){
		motorRightOn(duration);
		wait1Msec(duration);
	}
	else{
	
	}
}
